### PR TITLE
Issue #29 - Change order of settings

### LINKED ISSUE #29: Move the Bootswatch tab on the theme settings to top
We were discussing the fact that the Bootswatch options in Bootstrap Lite are pretty hidden and difficult to find, especially if you don't know what you are looking for. A user suggested that we move this tab on the settings page to the top to make it much easier for new users to the theme to notice these options. In some ways, for anyone using Bootstrap Lite without a sub-theme, this is the most important setting.

### PR DESCRIPTION
**Pull request by stpaultim**
Fixes #29

### CODE REVIEW

**Comment by stpaultim** [comment]
@bugfolder - Why don't you review this and merge it if it looks good to you?

**Comment by bugfolder** [comment]
Hmm, not to get too finicky, but I think Tweaks should still be above the CDN. Navbar, Breadcrumbs, and Tweaks are still things that affect the appearance that any user might want to play with, but CDN settings are advance-users only, and so should be on the bottom.

**Comment by stpaultim** [comment]
I'm fine with that.
 
Will fix PR in a few minutes.

**Comment by stpaultim** [comment]
bootstrap-tweaks

**Review by bugfolder — APPROVED** [review]
Looks good.

**Pull request merged**
